name: Fuse App For WII
run-name: Build Fuse App for WII / ${{ github.actor }} /

# Executed upon each commit pushed, merge commit in PR
on: [pull_request]

jobs:
  libspectrum:
    # Build libspectrum from the canonical SourceForge repository.
    # Only one case possible - without any libs, fake glib.
    name: "Libspectrum lib (WII)"
    uses: ./.github/workflows/build_libspectrum_wii_sub.yml
    with:
      key: fuse-app
      libspectrum_ref: master
      use_zlib: false
      use_bzip2: false
      use_libgcrypt: false
      use_libaudiofile: false
      use_fake_glib: true

#########################################
### SUPPORTED WII UI configurations ###
#########################################

### FIXME: Needs "yacc"
#  # NULL UI + sound
#  null-ui:
#    name: "Fuse NULL UI (WII)"
#    needs: [libspectrum]
#    uses: ./.github/workflows/build_wii_sub.yml
#    with:
#      name: "NULL UI"
#      dependencies: ""
#      configure_params: "--with-null-ui --with-audio-driver=null"
#      verify_ui: "null"
#      verify_audio: "null"

  # WII UI
  wii-ui:
    name: "Fuse WII UI (WII)"
    needs: [libspectrum]
    uses: ./.github/workflows/build_wii_sub.yml
    with:
      name: GTK3 UI
      dependencies: ""
      configure_params: "--with-wii"
      verify_ui: "wii"
      verify_audio: "wii"
