name: Windows release build
run-name: Build Windows release / ${{ github.actor }} /

on:
  workflow_dispatch:
    inputs:
      tag_name:
        type: string
        required: true
        description: Fuse tag to build, e.g. fuse-1.7.0
      libspectrum_url:
        type: string
        required: true
        description: URL of a released libspectrum source tarball

jobs:
  libspectrum:
    name: "Libspectrum (Windows)"
    runs-on: windows-latest
    timeout-minutes: 20
    env:
      CYGWIN_NOWINPATH: 1
      CPPFLAGS: "-I/usr/local/i686-w64-mingw32/include"
      LDFLAGS: "-L/usr/local/i686-w64-mingw32/lib"
      PKG_CONFIG_LIBDIR: "/usr/local/i686-w64-mingw32/lib/pkgconfig:/usr/i686-w64-mingw32/sys-root/mingw/lib/pkgconfig"
      CYGWIN_LIBDIR: "/usr/i686-w64-mingw32/sys-root/mingw/bin/"
    steps:
      - name: (1) Prepare environment
        run: |
          cd ${GITHUB_WORKSPACE}

          echo "Adjust autocrlf in git.."
          git config --global core.autocrlf input

          echo -n "Current directory: "
          pwd
          ls -la
        shell: bash

      - name: (2) Install Cygwin (32 bit) with libs
        uses: cygwin/cygwin-install-action@master
        with:
          platform: x86
          packages: |
            audiofile \
            autoconf \
            automake \
            bison \
            curl \
            flex \
            gcc-core \
            gcc-g++ \
            gettext-devel \
            libtool \
            libaudiofile-devel \
            make \
            mingw64-i686-audiofile \
            mingw64-i686-bzip2 \
            mingw64-i686-gcc-core \
            mingw64-i686-gcc-g++ \
            mingw64-i686-libgcrypt \
            mingw64-i686-libgpg-error \
            mingw64-i686-libpng \
            mingw64-i686-win-iconv \
            mingw64-i686-winpthread \
            mingw64-i686-zlib \
            pkg-config

      - name: (3) Download libspectrum source tarball
        run: |
          cd ${GITHUB_WORKSPACE}

          curl -L "${{ inputs.libspectrum_url }}" -o libspectrum.tar.gz
          mkdir libspectrum-src
          tar -xzf libspectrum.tar.gz -C libspectrum-src --strip-components=1
        shell: C:\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'

      - name: (4) Configure libspectrum
        run: |
          cd ${GITHUB_WORKSPACE}/libspectrum-src

          echo "Running configure .."
          if [ -x ./configure ]; then
            ./configure \
            --build=i686-pc-cygwin \
            --host=i686-w64-mingw32 \
            --prefix=/usr/local/i686-w64-mingw32 \
            --disable-static \
            --with-fake-glib \
            |& tee ./configure.out
          else
            ./autogen.sh
            ./configure \
            --build=i686-pc-cygwin \
            --host=i686-w64-mingw32 \
            --prefix=/usr/local/i686-w64-mingw32 \
            --disable-static \
            --with-fake-glib \
            |& tee ./configure.out
          fi
        shell: C:\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'

      - name: (5) Verify output from configure
        run: |
          cd ${GITHUB_WORKSPACE}/libspectrum-src

          grep -q "libspectrum is ready to be compiled" configure.out
          grep -q "zlib support: yes" configure.out
          grep -q "bzip2 support: yes" configure.out
          grep -q "libgcrypt support: yes" configure.out
          grep -q "libaudiofile support: yes" configure.out
          grep -q "Internal GLib replacement: yes" configure.out
        shell: C:\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'

      - name: (6) Make
        run: |
          cd ${GITHUB_WORKSPACE}/libspectrum-src

          echo "Running make .."
          make
        shell: C:\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'

      - name: (7) Install
        run: |
          cd ${GITHUB_WORKSPACE}/libspectrum-src

          echo "Running make install-strip .."
          make install-strip
        shell: C:\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'

      - name: (8) Copy dependency dlls
        run: |
          cd ${GITHUB_WORKSPACE}/libspectrum-src

          echo "Copying mandatory dependency dlls.."
          cp -f ${CYGWIN_LIBDIR}libgcc_s_sjlj-1.dll .
          cp -f ${CYGWIN_LIBDIR}libwinpthread-1.dll .
          cp -f ${CYGWIN_LIBDIR}libgpg-error-0.dll .
          cp -f ${CYGWIN_LIBDIR}libstdc++-6.dll .
          cp -f ${CYGWIN_LIBDIR}libgcc_s_sjlj-1.dll /usr/local/i686-w64-mingw32/bin/
          cp -f ${CYGWIN_LIBDIR}libwinpthread-1.dll /usr/local/i686-w64-mingw32/bin/
          cp -f ${CYGWIN_LIBDIR}libgpg-error-0.dll /usr/local/i686-w64-mingw32/bin/
          cp -f ${CYGWIN_LIBDIR}libstdc++-6.dll /usr/local/i686-w64-mingw32/bin/

          echo "Copying optional dependency dlls.."
          cp -f ${CYGWIN_LIBDIR}zlib1.dll . || true
          cp -f ${CYGWIN_LIBDIR}libbz2-1.dll . || true
          cp -f ${CYGWIN_LIBDIR}libgcrypt-20.dll . || true
          cp -f ${CYGWIN_LIBDIR}libaudiofile-1.dll . || true
          cp -f ${CYGWIN_LIBDIR}libFLAC-8.dll . || true
          cp -f ${CYGWIN_LIBDIR}libOGG-0.dll . || true
          cp -f ${CYGWIN_LIBDIR}zlib1.dll /usr/local/i686-w64-mingw32/bin/ || true
          cp -f ${CYGWIN_LIBDIR}libbz2-1.dll /usr/local/i686-w64-mingw32/bin/ || true
          cp -f ${CYGWIN_LIBDIR}libgcrypt-20.dll /usr/local/i686-w64-mingw32/bin/ || true
          cp -f ${CYGWIN_LIBDIR}libaudiofile-1.dll /usr/local/i686-w64-mingw32/bin/ || true
          cp -f ${CYGWIN_LIBDIR}libFLAC-8.dll /usr/local/i686-w64-mingw32/bin/ || true
          cp -f ${CYGWIN_LIBDIR}libOGG-0.dll /usr/local/i686-w64-mingw32/bin/ || true

          echo "Copying own dll.."
          cp -f .libs/libspectrum-*.dll /usr/local/i686-w64-mingw32/bin/
        shell: C:\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'

      - name: (9) Run tests
        run: |
          cd ${GITHUB_WORKSPACE}/libspectrum-src

          echo "Bulding and running tests .."
          make check
        shell: C:\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'

      - name: (10) Pack installed library files
        run: |
          cd ${GITHUB_WORKSPACE}

          tar -cvf libspectrum-installed-windows.tar -C /usr/local/i686-w64-mingw32/ .
        shell: C:\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'

      - name: (11) Upload libspectrum artifact
        uses: actions/upload-artifact@v4
        with:
          name: libspectrum-installed-windows-fuse-app
          path: libspectrum-installed-windows.tar

  fuse:
    name: "Fuse Win32 installer"
    needs: [libspectrum]
    uses: ./.github/workflows/build_windows_sub.yml
    with:
      key: "win32-installer"
      ref: "refs/tags/${{ inputs.tag_name }}"
      dependencies: "mingw64-i686-libxml2"
      configure_params: "--with-win32"
      package_target: "dist-win32-exe"
      verify_ui: "win32"
      verify_libxml2: "yes"
      verify_audio: "directsound"
      upload_artifacts: true
